import React from 'react';
import { 
  Lightbulb,
  Code,
  PenTool,
  BarChart3,
  Camera,
  Edit3,
  Type,
  Share2,
  BookOpen,
  Video,
  Megaphone,
  Palette,
  Search,
  Mail,
  TrendingUp,
  Users,
  Brain,
  Sparkles,
  Zap,
  Target,
  ShoppingCart,
  Heart,
  MessageSquare,
  FileText,
  LucideIcon,
  // Novos ícones
  Monitor,
  Smartphone,
  Globe,
  Database,
  Server,
  Cloud,
  Shield,
  Lock,
  Key,
  Settings,
  Wrench,
  Hammer,
  Puzzle,
  Layers,
  Box,
  Package,
  Truck,
  MapPin,
  Navigation,
  Compass,
  Map,
  Calculator,
  PieChart,
  LineChart,
  Activity,
  Wifi,
  Radio,
  Bluetooth,
  Cpu,
  HardDrive,
  Mic,
  Headphones,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Music,
  Image,
  Film,
  FileImage,
  FileVideo,
  Download,
  Upload,
  Link,
  ExternalLink,
  Copy,
  Clipboard,
  Scissors,
  Filter,
  Layers3,
  Grid3X3,
  Layout,
  Maximize,
  Minimize,
  Move,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Power,
  Battery,
  Plug,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Star,
  Award,
  Trophy,
  Medal,
  Crown,
  Gem,
  Diamond,
  Gift,
  PartyPopper,
  Cake,
  Coffee,
  Pizza,
  Utensils,
  ChefHat,
  Car,
  Plane,
  Train,
  Ship,
  Bike,
  Rocket,
  TreePine,
  Leaf,
  Flower,
  Sprout,
  Mountain,
  Waves,
  Building,
  Home,
  Store,
  School,
  Hospital,
  Factory,
  Briefcase,
  GraduationCap,
  BookOpenCheck,
  PenTool as Pen,
  Ruler,
  Scissors as Cut,
  Paintbrush,
  Archive,
  Folder,
  FolderOpen,
  File,
  FileSpreadsheet,
  FileBarChart,
  Newspaper,
  Bookmark,
  Tag,
  Tags,
  Calendar,
  Clock,
  Timer,
  Bell,
  BellRing,
  Phone,
  PhoneCall,
  MessageCircle,
  MessageSquareText,
  AtSign,
  Hash,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  CreditCard,
  Wallet,
  Coins,
  Receipt,
  Scale,
  Gavel,
  Eye,
  EyeOff,
  Glasses,
  Telescope,
  Microscope,
  Stethoscope,
  Thermometer,
  Syringe,
  Pill,
  Cross,
  Plus,
  Minus,
  X,
  Check,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  AlertTriangle,
  ShieldAlert,
  ShieldCheck,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  Users2,
  UserCircle,
  Contact,
  Handshake,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Angry,
  Laugh,
  Zap as Lightning,
  Beaker,
  FlaskConical,
  TestTube,
  Dna,
  Atom,
  Magnet,
  Orbit,
  Telescope as Scope,
  ChartBar,
  ChartLine,
  ChartPie,
  ChartNoAxesCombined
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  // Básicos/Originais
  'lightbulb': Lightbulb,
  'brain': Brain,
  'sparkles': Sparkles,
  'zap': Zap,
  'target': Target,
  'heart': Heart,
  
  // Tecnologia e Código
  'code': Code,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'globe': Globe,
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'wifi': Wifi,
  'radio': Radio,
  'bluetooth': Bluetooth,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  
  // Design e Criação
  'pen-tool': PenTool,
  'edit-3': Edit3,
  'type': Type,
  'palette': Palette,
  'camera': Camera,
  'image': Image,
  'film': Film,
  'paintbrush': Paintbrush,
  'layers': Layers,
  'layers-3': Layers3,
  'grid-3x3': Grid3X3,
  'layout': Layout,
  
  // Análise e Dados
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  'activity': Activity,
  'calculator': Calculator,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-no-axes-combined': ChartNoAxesCombined,
  
  // Comunicação e Social
  'share-2': Share2,
  'mail': Mail,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'message-square-text': MessageSquareText,
  'phone': Phone,
  'phone-call': PhoneCall,
  'megaphone': Megaphone,
  'mic': Mic,
  'headphones': Headphones,
  'at-sign': AtSign,
  
  // Usuários e Pessoas
  'users': Users,
  'users-2': Users2,
  'user-circle': UserCircle,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'contact': Contact,
  'handshake': Handshake,
  
  // Arquivos e Documentos
  'file-text': FileText,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'newspaper': Newspaper,
  'file-image': FileImage,
  'file-video': FileVideo,
  'file-spreadsheet': FileSpreadsheet,
  'file-bar-chart': FileBarChart,
  'folder': Folder,
  'folder-open': FolderOpen,
  'archive': Archive,
  
  // E-commerce e Negócios
  'shopping-cart': ShoppingCart,
  'store': Store,
  'briefcase': Briefcase,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'coins': Coins,
  'receipt': Receipt,
  'package': Package,
  'truck': Truck,
  
  // Segurança
  'shield': Shield,
  'lock': Lock,
  'key': Key,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  
  // Ferramentas e Configurações
  'settings': Settings,
  'wrench': Wrench,
  'hammer': Hammer,
  'ruler': Ruler,
  'scissors': Cut,
  
  // Navegação e Mapas
  'search': Search,
  'map-pin': MapPin,
  'navigation': Navigation,
  'compass': Compass,
  'map': Map,
  'move': Move,
  'external-link': ExternalLink,
  'link': Link,
  
  // Mídia e Entretenimento
  'video': Video,
  'play': Play,
  'pause': Pause,
  'skip-forward': SkipForward,
  'skip-back': SkipBack,
  'music': Music,
  'volume-2': Volume2,
  
  // Natureza e Elementos
  'sun': Sun,
  'moon': Moon,
  'star': Star,
  'flame': Flame,
  'snowflake': Snowflake,
  'tree-pine': TreePine,
  'leaf': Leaf,
  'flower': Flower,
  'sprout': Sprout,
  'mountain': Mountain,
  'waves': Waves,
  
  // Construções e Lugares
  'building': Building,
  'home': Home,
  'school': School,
  'hospital': Hospital,
  'factory': Factory,
  
  // Transporte
  'car': Car,
  'plane': Plane,
  'train': Train,
  'ship': Ship,
  'bike': Bike,
  'rocket': Rocket,
  
  // Prêmios e Conquistas
  'award': Award,
  'trophy': Trophy,
  'medal': Medal,
  'crown': Crown,
  'gem': Gem,
  'diamond': Diamond,
  
  // Festivo e Diversão
  'gift': Gift,
  'party-popper': PartyPopper,
  'cake': Cake,
  'coffee': Coffee,
  'pizza': Pizza,
  'utensils': Utensils,
  'chef-hat': ChefHat,
  
  // Tempo e Organização
  'calendar': Calendar,
  'clock': Clock,
  'timer': Timer,
  'bell': Bell,
  'bell-ring': BellRing,
  
  // Tags e Marcadores
  'bookmark': Bookmark,
  'tag': Tag,
  'tags': Tags,
  'hash': Hash,
  'percent': Percent,
  
  // Ciência e Medicina
  'beaker': Beaker,
  'flask-conical': FlaskConical,
  'test-tube': TestTube,
  'dna': Dna,
  'atom': Atom,
  'magnet': Magnet,
  'orbit': Orbit,
  'telescope': Telescope,
  'microscope': Microscope,
  'stethoscope': Stethoscope,
  'thermometer': Thermometer,
  'syringe': Syringe,
  'pill': Pill,
  
  // Ações e Status
  'check': Check,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'info': Info,
  'help-circle': HelpCircle,
  'alert-triangle': AlertTriangle,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  
  // Emotes
  'smile': Smile,
  'frown': Frown,
  'meh': Meh,
  'angry': Angry,
  'laugh': Laugh,
  
  // Educação
  'graduation-cap': GraduationCap,
  
  // Energia e Poder
  'power': Power,
  'battery': Battery,
  'plug': Plug,
  'lightning': Lightning,
  
  // Ações de Arquivo
  'download': Download,
  'upload': Upload,
  'copy': Copy,
  'clipboard': Clipboard,
  'filter': Filter,
  'maximize': Maximize,
  'minimize': Minimize,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'refresh-cw': RefreshCw,
  
  // Visão
  'eye': Eye,
  'eye-off': EyeOff,
  'glasses': Glasses,
  
  // Outros
  'puzzle': Puzzle,
  'box': Box,
  'cross': Cross,
  'plus': Plus,
  'minus': Minus,
  'x': X,
  'scale': Scale,
  'gavel': Gavel
};

// Função para resolver ícone por nome
export function getIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || Lightbulb; // Fallback para Lightbulb
}

// Função para renderizar ícone - SEMPRE retorna um elemento React válido
export function renderIcon(iconName: string, props: any = {}) {
  const IconComponent = getIconComponent(iconName);
  return React.createElement(IconComponent, props);
}